spring:
  data:
    rest:
      base-path: /api/
  datasource:
    url: jdbc:mysql://localhost/rsm_test?useSSL=false
    username: rsm
    password: rsm31234
    validation-query: SELECT 1
    test-on-borrow: true
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: false
      dialect: org.hibernate.dialect.MySQL5
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: false
        
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml